### ISSUE TITLE
Use of babashka in this project

### ISSUE THREAD

**Issue by guojing0** [prestancedesign/babashka-htmx-todoapp#1]
Hi,

I am thinking about learning ctmx and found your project really interesting. It's mentioned on your website that you used babashka and ctmx together. After browsing the code, I found that babashka was only used in the first or two lines or so.

So I was wondering that could you tell me what's the use of babashka in this case? Can I just, say, remove babashka-related code and use Clojure and lein for this?

Thank you for your time.

**Comment by prestancedesign** [comment]
Hi,

Thanks you for feedback and sorry for the delay, I didn't get the notification.

Yes I confirm, you can run with Clojure with only minor changes.
I just created this gist so you can play with it and Clojure CLI: https://gist.github.com/prestancedesign/cb86dc4334b3c190e8e46a0cdc5953a7

Cheers.

**Comment by guojing0** [comment]
Thank you.

Jing
2023年1月13日 +0100 12:36 Michael Salihi ***@***.***>，写道：
